title: The GIT of awesomeness
author: another Padwan GIT
email: tonylo.moby@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  This is a new site for learning and testing GITHUB. I may not know everything or even anything but I do know I can learnt it. 
  Which is all I need to know.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
